---
- name: Receive webhook events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 8000
  rules:
    - name: Event
      condition: event.payload.message == "Automate Everything with Ansible   "
      action:
        run_playbook:
          name: playbook.yml
