---
- name: Check services
  hosts: all
  tasks:
  - name: httpd and sshd are running
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
    loop:
      - apache2
      - sshd
