---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'automationhub.example.com/ee-minimal-rhel8:latest'
ansible_config: 'ansible.cfg'
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools    
  append:
    - RUN ls -al /
