---
- name: API GET method
  hosts: all
  vars:
    server: "https://reqres.in"
    endpoint: "/api/users?page=2"
  tasks:
    - name: Reqres list users
      ansible.builtin.uri:
        url: "{{ server }}{{ endpoint }}"
        method: GET
        status_code: 200
        timeout: 30
      register: result

    - name: Reqres print
      ansible.builtin.debug:
        var: result.json.data
