---
- name: template module
  hosts: all
  vars:
    toggle: true
    servers:
      host01:
        ip: 192.168.1.11
        type: large
      host02:
        ip: 192.168.1.12
        type: small
  tasks:
    - name: Apply template
      ansible.builtin.template:
        src: templates/type.txt.j2
        dest: type.txt
