---
- name: Listing files
  hosts: all
  tasks:
    - name: List file(s) and folder(s)
      ansible.builtin.shell: 'ls -l *'
      register: command_output

    - name: Command output
      ansible.builtin.debug:
        var: command_output.stdout_lines
