---
- name: Troubleshooting example
  hosts: all
  become: true
  vars:
    servers:
      host01:
        ip: 192.168.1.11
        type: large
  tasks:
  - name: print a fact
    ansible.builtin.debug:
      var: ansible_facts['architecture']

    - name: Latest apache2 package
      ansible.builtin.apt:
      name: apache2
        state: latest
        update_cache: true

    - name: Only large machines
      ansible.builtin.debug:
        msg: "{{ servers.values() | selectattr('type', 'eq', 'large') | map(attribute='ip') | join(',') }}"
