---
- name: Powershell playbook
  hosts: all
  tasks:
    - name: Check getdate
      ansible.windows.win_shell: |
        hostname
        Get-Date        
      register: command_output
    - name: Command output
      ansible.builtin.debug:
        var: command_output.stdout_lines
