---
- name: Kubernetes namespace present
  hosts: all
  tasks:
    - name:  Kubernetes namespace present
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "AutomateEverythingWithAnsible"
        state: present
