---
- name: Rolling update
  hosts: all
  become: true
  tasks:
    - name: Latest apache2 package
      ansible.builtin.apt:
        name: apache2
        state: latest
        update_cache: true
      notify: Apache restart
  handlers:
    - name: Apache restart
      ansible.builtin.service:
        name: apache2
      state: restarted
